# Setup
title: Tag
description: 함께 일하는 것을 제일 좋아합니다.
url: https://Haesus.github.io
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg
future: true

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag

#twitter:
#  username: vszhub
#  card: summary
#logo: logo.png

social:
  name: Haesus
  links:
#    - https://twitter.com/vszhub
    - https://github.com/Haesus
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Haesu Youn
  url: https://github.com/Haesus/
  email: sea15510@gmail.com
